version: 2
updates:
  # npm в корне
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees: ["puffynNeroun"]
    labels: ["deps", "automated"]
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:10"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees: ["puffynNeroun"]
    labels: ["deps", "actions", "automated"]
