name: Generate GitHub Metrics
on:
  schedule:
    - cron: '0 */12 * * *'   # каждые 12 часов
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: puffynNeroun
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_achievements_threshold: C
          config_timezone: UTC
          filename: github-metrics.svg
