name: Seed labels (one-time)
on: workflow_dispatch

permissions:
  issues: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Create labels
        uses: actions/github-script@v8
        with:
          script: |
            const labels = [
              { name: "deps", color: "0E8A16", description: "Dependency updates" },
              { name: "actions", color: "0366D6", description: "GitHub Actions updates" },
              { name: "automated", color: "5319E7", description: "Created by automation" }
            ];
            for (const l of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: l.name,
                  color: l.color,
                  description: l.description
                });
                core.info(`Created: ${l.name}`);
              } catch (e) {
                if (e.status === 422) {
                  core.info(`Exists: ${l.name}`);
                } else {
                  throw e;
                }
              }
            }
