name: Update README (variable times per day)

on:
  schedule:
    - cron: "7 * * * *"   # раз в час
  workflow_dispatch:

permissions:
  contents: write

# NEW: отменяем параллельные запуски этого workflow
concurrency:
  group: readme-auto-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # NEW: нужен полный граф для rebase

      - name: Decide and update
        id: run
        shell: bash
        run: |
          set -euo pipefail
          TODAY="$(date -u +%Y-%m-%d)"
          TS="$(date -u +"%Y-%m-%d %H:%M UTC")"

          START_LINE=$(grep -n "<!-- ACTIVITY:STATE" README.md | cut -d: -f1)
          END_LINE=$(grep -n "ACTIVITY:STATE -->" README.md | cut -d: -f1)
          if [[ -z "${START_LINE}" || -z "${END_LINE}" ]]; then
            echo "STATE block not found. Abort."
            exit 1
          fi

          STATE=$(sed -n "$((START_LINE+1)),$((END_LINE-1))p" README.md)
          DATE=$(echo "$STATE"  | grep '^DATE='   | cut -d= -f2- || true)
          COUNT=$(echo "$STATE" | grep '^COUNT='  | cut -d= -f2- || true)
          TARGET=$(echo "$STATE"| grep '^TARGET=' | cut -d= -f2- || true)
          COUNT=${COUNT:-0}; TARGET=${TARGET:-0}

          # Новый день → выбираем цель 1/2/5
          if [[ "$DATE" != "$TODAY" ]]; then
            RAND=$((RANDOM%100))
            if   (( RAND < 60 )); then TARGET=1
            elif (( RAND < 90 )); then TARGET=2
            else TARGET=5
            fi
            COUNT=0
            DATE="$TODAY"
            NEW_DAY="yes"
          else
            NEW_DAY="no"
          fi

          # Уже достигли цели? Ничего не делаем
          if (( COUNT >= TARGET )); then
            echo "NothingToDo=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Вероятностное решение — обновляться сейчас или позже
          CHANCE=$((RANDOM%100))
          if   (( TARGET==1 && CHANCE<35 )) || \
               (( TARGET==2 && CHANCE<45 )) || \
               (( TARGET==5 && CHANCE<70 )); then
            SHOULD_UPDATE="yes"
          else
            SHOULD_UPDATE="no"
          fi
          if [[ "$SHOULD_UPDATE" != "yes" && "$NEW_DAY" == "no" ]]; then
            echo "NothingToDo=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Видимый сниппет
          topics=("RSC patterns" "Server Actions" "TanStack Query v5" "Prisma schema" "Playwright e2e" "Core Web Vitals" "CI/CD" "NextAuth/SSO" "Redis caching")
          pick=${topics[$RANDOM % ${#topics[@]}]}
          SNIPPET="Last update: **$TS** · Focus today: *$pick*."

          # Вставка сниппета
          awk -v repl="$SNIPPET" '
            BEGIN{inblk=0}
            /<!-- ACTIVITY:START -->/ {print; print repl; inblk=1; next}
            /<!-- ACTIVITY:END -->/   {print; inblk=0; next}
            !inblk {print}
          ' README.md > README.tmp && mv README.tmp README.md

          # Обновление STATE
          COUNT=$((COUNT+1))
          awk -v date="$DATE" -v count="$COUNT" -v target="$TARGET" '
            BEGIN{inblk=0}
            /<!-- ACTIVITY:STATE/ {print; inblk=1; print "DATE="date; print "COUNT="count; print "TARGET="target; next}
            /ACTIVITY:STATE -->/  {print; inblk=0; next}
            !inblk {print}
          ' README.md > README.tmp && mv README.tmp README.md

          echo "NothingToDo=false" >> $GITHUB_OUTPUT

      # NEW: перед пушем ребейзим на удалённую ветку
      - name: Rebase onto remote
        if: steps.run.outputs.NothingToDo == 'false'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git rebase origin/master || git reset --hard origin/master

      - name: Commit changes
        if: steps.run.outputs.NothingToDo == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto refresh"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          file_pattern: README.md
          # NEW: на случай гонок — безопасный форс-пуш
          push_options: '--force-with-lease'
