name: Update README (variable 5–20 per day)

on:
  schedule:
    - cron: "*/15 * * * *"   # каждые 15 минут
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: readme-auto-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: run
        shell: bash
        run: |
          set -euo pipefail
          TODAY="$(date -u +%Y-%m-%d)"
          TS="$(date -u +"%Y-%m-%d %H:%M UTC")"
          HOUR=$(date -u +%H)

          # Разрешаем обновления только днём (05–22 UTC ~ 08–01 IL)
          if (( HOUR < 5 || HOUR > 22 )); then
            echo "NothingToDo=true" >> $GITHUB_OUTPUT; exit 0
          fi

          START_LINE=$(grep -n "<!-- ACTIVITY:STATE" README.md | cut -d: -f1)
          END_LINE=$(grep -n "ACTIVITY:STATE -->" README.md | cut -d: -f1)
          if [[ -z "${START_LINE}" || -z "${END_LINE}" ]]; then
            echo "STATE block not found. Abort."; exit 1
          fi

          STATE=$(sed -n "$((START_LINE+1)),$((END_LINE-1))p" README.md)
          DATE=$(echo "$STATE"  | grep '^DATE='   | cut -d= -f2- || true)
          COUNT=$(echo "$STATE" | grep '^COUNT='  | cut -d= -f2- || true)
          TARGET=$(echo "$STATE"| grep '^TARGET=' | cut -d= -f2- || true)
          COUNT=${COUNT:-0}; TARGET=${TARGET:-0}

          # Новый день → цель 5–20 с перекосом к 6–12
          if [[ "$DATE" != "$TODAY" ]]; then
            # распределение: 5–8 (35%), 9–12 (35%), 13–16 (20%), 17–20 (10%)
            R=$((RANDOM%100))
            if   (( R < 35 )); then TARGET=$((5 + RANDOM%4))     # 5–8
            elif (( R < 70 )); then TARGET=$((9 + RANDOM%4))     # 9–12
            elif (( R < 90 )); then TARGET=$((13 + RANDOM%4))    # 13–16
            else                   TARGET=$((17 + RANDOM%4))     # 17–20
            fi
            COUNT=0; DATE="$TODAY"; NEW_DAY="yes"
          else
            NEW_DAY="no"
          fi

          # Уже достигли цели — выходим
          if (( COUNT >= TARGET )); then
            echo "NothingToDo=true" >> $GITHUB_OUTPUT; exit 0
          fi

          # Вероятность апдейта сейчас (чтобы растягивать по дню):
          # чем дальше от цели, тем выше шанс
          GAP=$((TARGET-COUNT))
          BASE=$(( 30 + (GAP*5) ))      # 30% + 5% за каждый недостающий апдейт
          (( BASE > 85 )) && BASE=85
          CHANCE=$((RANDOM%100))
          if (( CHANCE >= BASE )) && [[ "$NEW_DAY" == "no" ]]; then
            echo "NothingToDo=true" >> $GITHUB_OUTPUT; exit 0
          fi

          topics=("RSC patterns" "Server Actions" "TanStack Query v5" "Prisma schema"
                  "Playwright e2e" "Core Web Vitals" "CI/CD" "NextAuth/SSO" "Redis caching")
          pick=${topics[$RANDOM % ${#topics[@]}]}
          SNIPPET="Last update: **$TS** · Focus today: *$pick*."

          # Вставка видимого сниппета
          awk -v repl="$SNIPPET" '
            BEGIN{inblk=0}
            /<!-- ACTIVITY:START -->/ {print; print repl; inblk=1; next}
            /<!-- ACTIVITY:END -->/   {print; inblk=0; next}
            !inblk {print}
          ' README.md > README.tmp && mv README.tmp README.md

          # Обновление STATE
          COUNT=$((COUNT+1))
          awk -v date="$DATE" -v count="$COUNT" -v target="$TARGET" '
            BEGIN{inblk=0}
            /<!-- ACTIVITY:STATE/ {print; inblk=1; print "DATE="date; print "COUNT="count; print "TARGET="target; next}
            /ACTIVITY:STATE -->/  {print; inblk=0; next}
            !inblk {print}
          ' README.md > README.tmp && mv README.tmp README.md

          echo "NothingToDo=false" >> $GITHUB_OUTPUT

      - name: Rebase onto remote
        if: steps.run.outputs.NothingToDo == 'false'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git rebase origin/master || git reset --hard origin/master

      - name: Commit changes
        if: steps.run.outputs.NothingToDo == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto refresh"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          file_pattern: README.md
          push_options: '--force-with-lease'
